import { ArrowRight, Bot, Braces, Check, LockKeyhole, Play, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";

const capabilities = [
  [Bot, "Autonomous execution", "Turn a brief into a plan, implementation, verification, and a repair loop."],
  [Braces, "A real workspace", "Files, code, diffs, preview, terminal, and Git history in one focused surface."],
  [LockKeyhole, "Safe by design", "Provider boundaries, approvals, workspace isolation, and no hidden credential access."],
];

export function LandingPage(): JSX.Element {
  return <div className="landing">
    <header className="topbar"><Link className="brand" to="/"><span className="brand-mark">B</span> BUILD <span>&amp;</span> CODE</Link><nav><a href="#workflow">Workflow</a><a href="#security">Security</a><Link to="/login">Sign in</Link><Link className="button button-primary button-small" to="/dashboard">Open workspace <ArrowRight data-icon="inline-end" /></Link></nav></header>
    <main>
      <section className="hero page-shell"><div className="hero-copy"><span className="eyebrow"><Sparkles data-icon="inline-start" /> AUTONOMOUS ENGINEERING WORKSPACE</span><h1>Describe it.<br /><em>Build it.</em><br />Ship it.</h1><p>Build, code, test, debug, preview, and ship software with an autonomous AI engineering workspace that keeps every decision observable.</p><div className="hero-actions"><Link className="button button-primary" to="/dashboard">Start building <ArrowRight data-icon="inline-end" /></Link><a className="button button-ghost" href="#preview"><Play data-icon="inline-start" /> See how it works</a></div><div className="trust-row"><span><Check data-icon="inline-start" /> No hidden execution</span><span><Check data-icon="inline-start" /> Diff before apply</span><span><Check data-icon="inline-start" /> Git-ready</span></div></div><div className="hero-console" id="preview"><div className="window-bar"><span className="window-dots">● ● ●</span><span>creator-analytics / agent-run</span><span>⌘ K</span></div><div className="console-grid"><aside><span className="muted-label">EXPLORER</span><b>▾ creator-analytics</b><span>  ◇ src</span><span>  ◇ dashboard.tsx</span><span>  ◇ metrics.ts</span><span>  ◇ package.json</span><span>  ◇ README.md</span></aside><div className="code-preview"><div className="code-line"><i>01</i><span><strong>const</strong> dashboard = <mark>await</mark> build({"{"}</span></div><div className="code-line"><i>02</i><span>  intent: <u>“creator analytics”</u>,</span></div><div className="code-line"><i>03</i><span>  framework: <u>“react-vite”</u>,</span></div><div className="code-line"><i>04</i><span>  verification: <strong>true</strong>,</span></div><div className="code-line"><i>05</i><span>{"}"});</span></div><div className="agent-note"><span className="status-dot" /> Agent verified build <b>4/4</b><small>2m 14s</small></div></div></div></div></section>
      <section className="section page-shell" id="workflow"><div className="section-heading"><span className="eyebrow">ONE LOOP, FULLY OBSERVABLE</span><h2>From first sentence<br />to working software.</h2><p>Every action is a structured event you can inspect, approve, and replay.</p></div><div className="workflow-strip">{["Understand", "Plan", "Execute", "Verify", "Repair", "Ship"].map((step, index) => <div className="workflow-step" key={step}><span>0{index + 1}</span><strong>{step}</strong>{index < 5 && <ArrowRight />}</div>)}</div></section>
      <section className="section section-muted page-shell"><div className="section-heading"><span className="eyebrow">BUILT FOR THE WORK</span><h2>Not another chat box.</h2><p>A calm, high-density command center for serious product work.</p></div><div className="capability-grid">{capabilities.map(([Icon, title, text]) => <article className="capability" key={title as string}><Icon /><h3>{title as string}</h3><p>{text as string}</p></article>)}</div></section>
      <section className="security-band page-shell" id="security"><div><span className="eyebrow"><LockKeyhole data-icon="inline-start" /> SECURITY FIRST</span><h2>Your code stays in its lane.</h2><p>Generated workspaces are designed to run behind explicit sandbox interfaces with limits, approvals, and secret boundaries. No .env files. No silent pushes.</p></div><div className="security-list"><span><Check /> Path validation</span><span><Check /> Command allowlists</span><span><Check /> Approval gates</span><span><Check /> Structured audit trail</span></div></section>
    </main><footer className="footer page-shell"><Link className="brand" to="/"><span className="brand-mark">B</span> BUILD &amp; CODE</Link><span>Describe it. Build it. Ship it.</span><span>© 2026 Build &amp; Code</span></footer>
  </div>;
}
